### ISSUE TITLE
Send a response to the sender when an email has been successfully processed

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/clownfish#8]
Based on user feedback, we should introduce more user interaction to the clownfish application.  When a user successfully sends a message that is received, we should respond to them with a message confirming the receipt of the file and that it has been successfully uploaded.  This way, people feel like that application is working for them and not just a black box.

To complete this issue, a developer needs to:
 1. Branch off of `development`.
 2. Import the `mailgun-js` library.
 3. Use the `mailgun-js` library to send an email [after the logger call](https://github.com/IMA-WorldHealth/clownfish/blob/master/index.js#L84) on line 84 of index.js
 4. The email should inform the user that their message was successfully archived, with the folder name and document name mentioned.

**Comment by jniles** [comment]
@jeremielodi, would you be able to work on this issue?

**Comment by jeremielodi** [comment]
Yes, let me give it a try!

**Comment by jniles** [comment]
Closed in #13
